### ISSUE TITLE
SyntaxError: Unexpected token import when I try to run node examples/booklist.js          

### ISSUE THREAD

**Issue by ishaan119** [bdickason/node-goodreads#30]
$ node examples/booklist.js          
import querystring from 'querystring';
^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ishaansutaria/test_gr/node-goodreads/index.js:5:18)
------------------------------------------------------------

**Comment by rharriso** [comment]
This is because `import` isn't valid, even in latest stable node. The example page would require a precompile step to run, and even them I'm not sure it would work.

It's really only useful as reference.
